import { Router } from "express";
import { createUser, listUsers, login, me, updateUser } from "../controllers/authController";
import { requireAuth, requireAdmin } from "../middleware/auth";
const router=Router();
router.post("/login",login);
router.get("/me",requireAuth,me);
router.get("/users",requireAuth,requireAdmin,listUsers);
router.post("/users",requireAuth,requireAdmin,createUser);
router.patch("/users/:id",requireAuth,requireAdmin,updateUser);
export default router;