import { Router } from "express";
import { addCarExpense,createCar,deleteCar,deleteCarExpense,downloadSaleDocument,getCar,getCarFinancials,listCarExpenses,listCarProfits,listCars,sellCar,updateCar,updateCarDocuments,updateCarExpense,updateCarStatus,uploadCarDocument,uploadSaleDocument } from "../controllers/carController";
import { carDocumentUpload } from "../middleware/carDocumentUpload";
import { requireAdmin,requireStaffOrAdmin } from "../middleware/auth";
const router=Router();
router.get("/",listCars);
router.get("/expenses",requireAdmin,listCarExpenses);
router.get("/profits",requireAdmin,listCarProfits);
router.post("/",createCar);
router.get("/:id",getCar);
router.post("/:id/documents/:documentKey",requireStaffOrAdmin,carDocumentUpload.single("file"),uploadCarDocument);
router.patch("/:id/documents",requireStaffOrAdmin,updateCarDocuments);
router.patch("/:id/status",requireAdmin,updateCarStatus);
router.patch("/:id",requireStaffOrAdmin,updateCar);
router.put("/:id",requireStaffOrAdmin,updateCar);
router.delete("/:id",requireAdmin,deleteCar);
router.get("/:id/financials",requireAdmin,getCarFinancials);
router.post("/:id/sale/documents/:documentKey",requireStaffOrAdmin,carDocumentUpload.single("file"),uploadSaleDocument);
router.get("/:id/sale/documents/:documentKey/download",requireAdmin,downloadSaleDocument);
router.post("/:id/expenses",requireAdmin,addCarExpense);
router.patch("/expenses/:expenseId",requireAdmin,updateCarExpense);
router.patch("/:id/expenses/:expenseId",requireAdmin,updateCarExpense);
router.delete("/:id/expenses/:expenseId",requireAdmin,deleteCarExpense);
router.post("/:id/sell",requireAdmin,sellCar);
export default router;