import { Router } from "express";
import { createCustomer,createCustomerDocumentUpload,completeCustomerDocumentUpload,uploadCustomerDocument,deleteCustomer,getCustomer,getCustomerHistory,listCustomers,updateCustomer,updateCustomerDocuments } from "../controllers/customerController";
import { requireAdmin } from "../middleware/auth";
import { customerDocumentUpload } from "../middleware/customerDocumentUpload";
const router=Router();
router.get("/",listCustomers);
router.post("/",createCustomer);
router.get("/:id/history",getCustomerHistory);
router.post("/:id/documents/:documentKey/signature",createCustomerDocumentUpload);
router.post("/:id/documents/:documentKey/complete",completeCustomerDocumentUpload);
router.post("/:id/documents/:documentKey",customerDocumentUpload.single("file"),uploadCustomerDocument);
router.patch("/:id/documents",updateCustomerDocuments);
router.get("/:id",getCustomer);
router.patch("/:id",updateCustomer);
router.put("/:id",updateCustomer);
router.delete("/:id",requireAdmin,deleteCustomer);
export default router;