import { Router } from "express";
import { requireAdmin } from "../middleware/auth";
import { createFollowUp,createLoan,deleteFollowUp,deleteLoan,getLoan,listFollowUps,listLoans,updateFollowUp,updateLoan,updateLoanStatus,updateLoanDocuments,uploadLoanDocument } from "../controllers/loanController";
import { loanDocumentUpload } from "../middleware/loanDocumentUpload";
const router=Router();
router.get("/follow-ups",listFollowUps);
router.get("/",listLoans);
router.post("/",createLoan);
router.get("/:id",getLoan);
router.post("/:id/documents/:documentKey",loanDocumentUpload.single("file"),uploadLoanDocument);
router.patch("/:id/documents",updateLoanDocuments);
router.patch("/:id",updateLoan);
router.put("/:id",updateLoan);
router.delete("/:id",requireAdmin,deleteLoan);
router.patch("/:id/status",updateLoanStatus);
router.get("/:id/follow-ups",listFollowUps);
router.post("/:id/follow-ups",createFollowUp);
router.patch("/:id/follow-ups/:followUpId",updateFollowUp);
router.delete("/:id/follow-ups/:followUpId",requireAdmin,deleteFollowUp);
export default router;